### ISSUE TITLE
SignUp

### ISSUE THREAD

**Issue by JonnyMcMuff** [JonnyMcMuff/feinstrubbot#1]
As a User
I want to sign up
so that I get notifications

**Comment by JoGosGitHub** [comment]
5h

**Comment by nilres** [comment]
- [ ] Given a working telegram account when the user sends the registration string to the bot the user is notified about the registration result

- [ ] Given a registration fails because the user name is already in use the system should report that to the user

**Comment by akramer-dozent** [comment]
4h confirmed

**Comment by nilres** [comment]
Done in feature signup.

**Comment by akramer-dozent** [comment]
done
