### ISSUE TITLE
customize bot

### ISSUE THREAD

**Issue by JoGosGitHub** [JonnyMcMuff/feinstrubbot#10]
As a user,
I want to customize my bot via chat,
To get the best user experience

For example:
- I want to configure the bot in a way that he sends me only notifications in a given time frame (not at nighttime...)
- I get notifications for multiple locations
- I want that the bot calls me by my name
- I want to get a function that reports the available commands.

**Comment by JoGosGitHub** [comment]
4h

**Comment by smashingchrische** [comment]
[ ] Given that the user is registered to the service when the user writes some predetermined customizing command in the chat with the bot device, the bot should respond with the customizing status (succesfull / unsuccessfull) and save the customized options.

**Comment by akramer-dozent** [comment]
4h confirmed

**Comment by nilres** [comment]
Nico: Done

**Comment by akramer-dozent** [comment]
checked. done
