### ISSUE TITLE
Virtualized environment

### ISSUE THREAD

**Issue by smashingchrische** [JonnyMcMuff/feinstrubbot#11]
As a developer,
I want a virtualized environment,
so that I can run the bot independent from a particular hardware setup.

**Comment by JoGosGitHub** [comment]
3h

**Comment by smashingchrische** [comment]
- [ ] Given the full source code,
       when I start a build script / file
       then there will be a virtualized environment running the application

**Comment by akramer-dozent** [comment]
5h confirmed

**Comment by smashingchrische** [comment]
done - see pull request
