### ISSUE TITLE
Delete Users

### ISSUE THREAD

**Issue by JoGosGitHub** [JonnyMcMuff/feinstrubbot#12]
As an administrator,
I want to unsubscribe users
that are inactive over a certain time period.

**Comment by JoGosGitHub** [comment]
0.1h

**Comment by smashingchrische** [comment]
- [ ] Given that there is a valid administrator when the administrator has access to the database s/he can query the registered users and delete all that have not been active over a defined period (e.g. 2 years) of time.

**Comment by akramer-dozent** [comment]
2h confirmed

**Comment by akramer-dozent** [comment]
checked. done
