### ISSUE TITLE
Feinstaub Alarm

### ISSUE THREAD

**Issue by JoGosGitHub** [JonnyMcMuff/feinstrubbot#2]
As a user,
I want to get alerts when there is a Feinstaub Alarm,
To be informed

**Comment by JoGosGitHub** [comment]
Will also show information that the VVS tickets are cheaper

**Comment by JoGosGitHub** [comment]
1,5h

**Comment by nilres** [comment]
Given that the user is registered to the service when the Feinstaub-level is above a certain limit the user is notified about the Feinstaub Alarm

**Comment by akramer-dozent** [comment]
2h confirmed

**Comment by akramer-dozent** [comment]
checked. done
