### ISSUE TITLE
get airquality

### ISSUE THREAD

**Issue by JonnyMcMuff** [JonnyMcMuff/feinstrubbot#3]
As a user
I want to chat with the bot
so that I can get the current air quality

**Comment by JoGosGitHub** [comment]
1h

**Comment by nilres** [comment]
- [ ] Given that the user is registered to the service when the the user asks the bot the question "How is the air quality?" the user is notified about the level.

**Comment by akramer-dozent** [comment]
3h confirmed

**Comment by nilres** [comment]
Implemented in signup feature.

**Comment by akramer-dozent** [comment]
checked. done
