### ISSUE TITLE
set location

### ISSUE THREAD

**Issue by JonnyMcMuff** [JonnyMcMuff/feinstrubbot#4]
As a User
I want to set a location
so that I only get information about this location

**Comment by JoGosGitHub** [comment]
2h

**Comment by nilres** [comment]
- [ ] Given that the user is registered to the service when the user sends "My current location is xxxx" the data is updated in the backend
- [ ] Given the user has send a proper location update string the user gets a confirmation about the location change
- [ ] Given the user has send a bad location update string the user gets a error message

**Comment by akramer-dozent** [comment]
2h confirmed

**Comment by nilres** [comment]
Done!

**Comment by akramer-dozent** [comment]
checked. done
