### ISSUE TITLE
add to telegram group

### ISSUE THREAD

**Issue by JonnyMcMuff** [JonnyMcMuff/feinstrubbot#7]
As an user
I want to integrate the bot
so that I can add it into an existing telegram group.

**Comment by JoGosGitHub** [comment]
0.5h

**Comment by nilres** [comment]
- [ ] Given that the user is registered to the service when the user adds the bot to a group the group should get information about Feinstaub Alarm

**Comment by akramer-dozent** [comment]
1h confirmed

**Comment by JonnyMcMuff** [comment]
done

**Comment by akramer-dozent** [comment]
checked. done
