### ISSUE TITLE
bot connection to database

### ISSUE THREAD

**Issue by JonnyMcMuff** [JonnyMcMuff/feinstrubbot#9]
As a User
I want a bot that can connect to a database
so that i can receive dust data

**Comment by JoGosGitHub** [comment]
2h

**Comment by smashingchrische** [comment]
Given that there is a working setup of an external database, when the bot tries to connect to the database it should get a working connection and be able to retrieve user data. This can be tested using a Unit Test.

**Comment by akramer-dozent** [comment]
2h confirmed

**Comment by nilres** [comment]
Done in feature signup.

**Comment by akramer-dozent** [comment]
done
